FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
ADD build.tar.gz /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

#tar -czvf build.tar.gz dist/aston-villa-app/
#docker build -f Dockerfile-test -t test-image .
#docker run -d -p 8002:80 test-image