# Use an official Node.js runtime as a parent image
FROM node:12.7-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Install any needed packages specified in package.json
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Expose the port the app runs in
EXPOSE 4200

# Run the command to start the application
CMD ["npm", "start"]