name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:community
        ports:
          - 9000:9000
        options: >-
          --health-cmd "curl --silent --fail http://localhost:9000/api/system/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Wait for SonarQube to be ready
        run: |
          until curl --silent --fail http://localhost:9000/api/system/status; do
            echo "Waiting for SonarQube to start..."
            sleep 10
          done

      - name: Run SonarQube scan
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="http://localhost:9000" \
            -e SONAR_LOGIN="${{ secrets.SONAR_TOKEN }}" \
            -v "${{ github.workspace }}:/usr/src" \
            sonarsource/sonar-scanner-cli
